{{- range $.Values.deployments }}
---
apiVersion: v1
kind: Service

metadata:
  name: hello-{{ .name }}-{{ $.Release.Namespace }}

spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP

  selector:
    app: hello-{{ .name }}-{{ $.Release.Namespace }}
{{- end }}
