{{- range $.Values.deployments }}
---
apiVersion: v1
kind: Service

metadata:
  name: hello-{{ .name }}-service
  labels:
    run: hello-{{ .name }}-service

spec:
  ports:
  - port: 80
  selector:
    run: hello-{{ .name }}-service
{{- end }}
