---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hello-proj
  namespace: argocd

spec:
  description: Project for deployment of hello Application
  sourceRepos:
  - '*'
  destinations:
  - namespace: hello
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: 'ClusterRole'
  - group: '*'
    kind: 'ClusterRoleBinding'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

  orphanedResources:
    warn: false
